### ISSUE TITLE
Typo in manifests/openshift-state-metrics-cluster-role.yaml

### ISSUE THREAD

**Issue by shah-zobair** [wanghaoran1988/openshift-state-metrics#1]
Should be:

```
- apiGroups: ["quota.openshift.io"]
  resources:
  - **clusterresourcequotas**
  verbs: ["list", "watch"]`
```

Instead of:
```
- apiGroups: ["quota.openshift.io"]
  resources:
  - **clusterresourcequota**
  verbs: ["list", "watch"]
```

I can push this if you add me as a contributor. Thanks.
